name: Publish docs via GitHub Pages
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      
      - name: Nav auto create
        run: |
          mv mkdocs.example.yml mkdocs.yml
          php autonav.php

      - name: Check dir
        run: |
          mkdir docs
          mv SP/ docs/
          mv Wiki/ docs/
          mv Start/ docs/

      - name: Throw mkdocs.yml
        run: cat mkdocs.yml
      
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: paperclip.docs.fsky7.com
